
package edu.utep.trustlab.services;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ToolkitServices", targetNamespace = "http://services.trustlab.utep.edu", wsdlLocation = "http://iw.cs.utep.edu:8080/toolkits/services/ToolkitServices?wsdl")
public class ToolkitServices
    extends Service
{

    private final static URL TOOLKITSERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(edu.utep.trustlab.services.ToolkitServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = edu.utep.trustlab.services.ToolkitServices.class.getResource(".");
            url = new URL(baseUrl, "http://iw.cs.utep.edu:8080/toolkits/services/ToolkitServices?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://iw.cs.utep.edu:8080/toolkits/services/ToolkitServices?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TOOLKITSERVICES_WSDL_LOCATION = url;
    }

    public ToolkitServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToolkitServices() {
        super(TOOLKITSERVICES_WSDL_LOCATION, new QName("http://services.trustlab.utep.edu", "ToolkitServices"));
    }

    /**
     * 
     * @return
     *     returns ToolkitServicesPortType
     */
    @WebEndpoint(name = "ToolkitServicesHttpSoap11Endpoint")
    public ToolkitServicesPortType getToolkitServicesHttpSoap11Endpoint() {
        return super.getPort(new QName("http://services.trustlab.utep.edu", "ToolkitServicesHttpSoap11Endpoint"), ToolkitServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToolkitServicesPortType
     */
    @WebEndpoint(name = "ToolkitServicesHttpSoap11Endpoint")
    public ToolkitServicesPortType getToolkitServicesHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.trustlab.utep.edu", "ToolkitServicesHttpSoap11Endpoint"), ToolkitServicesPortType.class, features);
    }

}
