
package edu.utep.trustlab.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Tue Apr 17 15:20:29 MDT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "float2ShortThr", namespace = "http://services.trustlab.utep.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "float2ShortThr", namespace = "http://services.trustlab.utep.edu/", propOrder = {"url", "scalingFactor", "offset"})

public class Float2ShortThr {

    @XmlElement(name = "url")
    private java.lang.String url;
    @XmlElement(name = "scalingFactor")
    private java.lang.String scalingFactor;
    @XmlElement(name = "offset")
    private java.lang.String offset;

    public java.lang.String getUrl() {
        return this.url;
    }

    public void setUrl(java.lang.String newUrl)  {
        this.url = newUrl;
    }

    public java.lang.String getScalingFactor() {
        return this.scalingFactor;
    }

    public void setScalingFactor(java.lang.String newScalingFactor)  {
        this.scalingFactor = newScalingFactor;
    }

    public java.lang.String getOffset() {
        return this.offset;
    }

    public void setOffset(java.lang.String newOffset)  {
        this.offset = newOffset;
    }

}

