
package edu.utep.trustlab.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Tue Apr 17 15:20:30 MDT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "grdimage", namespace = "http://services.trustlab.utep.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grdimage", namespace = "http://services.trustlab.utep.edu/", propOrder = {"url", "C", "J", "B", "T", "R"})

public class Grdimage {

    @XmlElement(name = "url")
    private java.lang.String url;
    @XmlElement(name = "C")
    private java.lang.String C;
    @XmlElement(name = "J")
    private java.lang.String J;
    @XmlElement(name = "B")
    private java.lang.String B;
    @XmlElement(name = "T")
    private java.lang.String T;
    @XmlElement(name = "R")
    private java.lang.String R;

    public java.lang.String getUrl() {
        return this.url;
    }

    public void setUrl(java.lang.String newUrl)  {
        this.url = newUrl;
    }

    public java.lang.String getC() {
        return this.C;
    }

    public void setC(java.lang.String newC)  {
        this.C = newC;
    }

    public java.lang.String getJ() {
        return this.J;
    }

    public void setJ(java.lang.String newJ)  {
        this.J = newJ;
    }

    public java.lang.String getB() {
        return this.B;
    }

    public void setB(java.lang.String newB)  {
        this.B = newB;
    }

    public java.lang.String getT() {
        return this.T;
    }

    public void setT(java.lang.String newT)  {
        this.T = newT;
    }

    public java.lang.String getR() {
        return this.R;
    }

    public void setR(java.lang.String newR)  {
        this.R = newR;
    }

}

