
package edu.utep.trustlab.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Tue Apr 17 15:20:30 MDT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "netCDFTimeSeries", namespace = "http://services.trustlab.utep.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "netCDFTimeSeries", namespace = "http://services.trustlab.utep.edu/", propOrder = {"url", "lPlotVariablesList", "rPlotVariablesList", "xDimName", "xDimSize", "title", "yLAxisLabel", "yRAxisLabel"})

public class NetCDFTimeSeries {

    @XmlElement(name = "url")
    private java.lang.String url;
    @XmlElement(name = "lPlotVariablesList")
    private java.lang.String lPlotVariablesList;
    @XmlElement(name = "rPlotVariablesList")
    private java.lang.String rPlotVariablesList;
    @XmlElement(name = "xDimName")
    private java.lang.String xDimName;
    @XmlElement(name = "xDimSize")
    private java.lang.String xDimSize;
    @XmlElement(name = "title")
    private java.lang.String title;
    @XmlElement(name = "yLAxisLabel")
    private java.lang.String yLAxisLabel;
    @XmlElement(name = "yRAxisLabel")
    private java.lang.String yRAxisLabel;

    public java.lang.String getUrl() {
        return this.url;
    }

    public void setUrl(java.lang.String newUrl)  {
        this.url = newUrl;
    }

    public java.lang.String getLPlotVariablesList() {
        return this.lPlotVariablesList;
    }

    public void setLPlotVariablesList(java.lang.String newLPlotVariablesList)  {
        this.lPlotVariablesList = newLPlotVariablesList;
    }

    public java.lang.String getRPlotVariablesList() {
        return this.rPlotVariablesList;
    }

    public void setRPlotVariablesList(java.lang.String newRPlotVariablesList)  {
        this.rPlotVariablesList = newRPlotVariablesList;
    }

    public java.lang.String getXDimName() {
        return this.xDimName;
    }

    public void setXDimName(java.lang.String newXDimName)  {
        this.xDimName = newXDimName;
    }

    public java.lang.String getXDimSize() {
        return this.xDimSize;
    }

    public void setXDimSize(java.lang.String newXDimSize)  {
        this.xDimSize = newXDimSize;
    }

    public java.lang.String getTitle() {
        return this.title;
    }

    public void setTitle(java.lang.String newTitle)  {
        this.title = newTitle;
    }

    public java.lang.String getYLAxisLabel() {
        return this.yLAxisLabel;
    }

    public void setYLAxisLabel(java.lang.String newYLAxisLabel)  {
        this.yLAxisLabel = newYLAxisLabel;
    }

    public java.lang.String getYRAxisLabel() {
        return this.yRAxisLabel;
    }

    public void setYRAxisLabel(java.lang.String newYRAxisLabel)  {
        this.yRAxisLabel = newYRAxisLabel;
    }

}

