
package edu.utep.trustlab.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Tue Apr 17 15:20:30 MDT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "vtkImageDataReaderFloat", namespace = "http://services.trustlab.utep.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vtkImageDataReaderFloat", namespace = "http://services.trustlab.utep.edu/", propOrder = {"url", "littleEndian", "dim", "dataOrigin", "dataSpacing", "dataExtent", "numScalarComponents", "readLowerLeft"})

public class VtkImageDataReaderFloat {

    @XmlElement(name = "url")
    private java.lang.String url;
    @XmlElement(name = "littleEndian")
    private java.lang.String littleEndian;
    @XmlElement(name = "dim")
    private java.lang.String dim;
    @XmlElement(name = "dataOrigin")
    private java.lang.String dataOrigin;
    @XmlElement(name = "dataSpacing")
    private java.lang.String dataSpacing;
    @XmlElement(name = "dataExtent")
    private java.lang.String dataExtent;
    @XmlElement(name = "numScalarComponents")
    private java.lang.String numScalarComponents;
    @XmlElement(name = "readLowerLeft")
    private java.lang.String readLowerLeft;

    public java.lang.String getUrl() {
        return this.url;
    }

    public void setUrl(java.lang.String newUrl)  {
        this.url = newUrl;
    }

    public java.lang.String getLittleEndian() {
        return this.littleEndian;
    }

    public void setLittleEndian(java.lang.String newLittleEndian)  {
        this.littleEndian = newLittleEndian;
    }

    public java.lang.String getDim() {
        return this.dim;
    }

    public void setDim(java.lang.String newDim)  {
        this.dim = newDim;
    }

    public java.lang.String getDataOrigin() {
        return this.dataOrigin;
    }

    public void setDataOrigin(java.lang.String newDataOrigin)  {
        this.dataOrigin = newDataOrigin;
    }

    public java.lang.String getDataSpacing() {
        return this.dataSpacing;
    }

    public void setDataSpacing(java.lang.String newDataSpacing)  {
        this.dataSpacing = newDataSpacing;
    }

    public java.lang.String getDataExtent() {
        return this.dataExtent;
    }

    public void setDataExtent(java.lang.String newDataExtent)  {
        this.dataExtent = newDataExtent;
    }

    public java.lang.String getNumScalarComponents() {
        return this.numScalarComponents;
    }

    public void setNumScalarComponents(java.lang.String newNumScalarComponents)  {
        this.numScalarComponents = newNumScalarComponents;
    }

    public java.lang.String getReadLowerLeft() {
        return this.readLowerLeft;
    }

    public void setReadLowerLeft(java.lang.String newReadLowerLeft)  {
        this.readLowerLeft = newReadLowerLeft;
    }

}

