
package edu.utep.trustlab.services.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.5.2
 * Tue Apr 17 15:20:30 MDT 2012
 * Generated source version: 2.5.2
 */

@XmlRootElement(name = "vtkPolyDataMapper", namespace = "http://services.trustlab.utep.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vtkPolyDataMapper", namespace = "http://services.trustlab.utep.edu/", propOrder = {"url", "scalarRange", "xRotation", "yRotation", "zRotation", "size", "backgroundColor", "magnification"})

public class VtkPolyDataMapper {

    @XmlElement(name = "url")
    private java.lang.String url;
    @XmlElement(name = "scalarRange")
    private java.lang.String scalarRange;
    @XmlElement(name = "xRotation")
    private java.lang.String xRotation;
    @XmlElement(name = "yRotation")
    private java.lang.String yRotation;
    @XmlElement(name = "zRotation")
    private java.lang.String zRotation;
    @XmlElement(name = "size")
    private java.lang.String size;
    @XmlElement(name = "backgroundColor")
    private java.lang.String backgroundColor;
    @XmlElement(name = "magnification")
    private java.lang.String magnification;

    public java.lang.String getUrl() {
        return this.url;
    }

    public void setUrl(java.lang.String newUrl)  {
        this.url = newUrl;
    }

    public java.lang.String getScalarRange() {
        return this.scalarRange;
    }

    public void setScalarRange(java.lang.String newScalarRange)  {
        this.scalarRange = newScalarRange;
    }

    public java.lang.String getXRotation() {
        return this.xRotation;
    }

    public void setXRotation(java.lang.String newXRotation)  {
        this.xRotation = newXRotation;
    }

    public java.lang.String getYRotation() {
        return this.yRotation;
    }

    public void setYRotation(java.lang.String newYRotation)  {
        this.yRotation = newYRotation;
    }

    public java.lang.String getZRotation() {
        return this.zRotation;
    }

    public void setZRotation(java.lang.String newZRotation)  {
        this.zRotation = newZRotation;
    }

    public java.lang.String getSize() {
        return this.size;
    }

    public void setSize(java.lang.String newSize)  {
        this.size = newSize;
    }

    public java.lang.String getBackgroundColor() {
        return this.backgroundColor;
    }

    public void setBackgroundColor(java.lang.String newBackgroundColor)  {
        this.backgroundColor = newBackgroundColor;
    }

    public java.lang.String getMagnification() {
        return this.magnification;
    }

    public void setMagnification(java.lang.String newMagnification)  {
        this.magnification = newMagnification;
    }

}

