package edu.utep.trustlab.toolkitOperators.cmmf;
import edu.utep.trustlab.toolkitOperators.SimulationOperator;
import edu.utep.trustlab.toolkitOperators.util.CommandRunner;


public class Feawd extends SimulationOperator
{
	
	// the output name for the dataset generated by this operator
	private static final String outputFileName = "Feawd_out.xml";
	
	public Feawd(String datasetURL) {
		super(datasetURL, outputFileName);
	}

	/*
	 * This method accesses the functionality of the wrapped executable. In this example, the exectuable takes
	 * three params (param1, param2, and param3). You can extend this to take as many parameters as necessary. This
	 * examples assume that the executable takes an input file path and an output file path, where the result will be written.
	 */
	public String transform(
			String np,
			String nsteps,
			String max_load_factor,
			String mat)
	{
		
		String matFilePath = getInputFile("mat");
		
		//The command string that will be passed to the shell
		// mpirun –np #np ./feawd –nsteps #steps -max_load_factor lf -snes_monitor 
		//      -save_all -hdf5_out -response -nodal_stres -mat Materials.Ext
		String cmd = 
			"mpirun -np " + np + " " +
			"feawd " +
			"–nsteps " + nsteps + " " +
			"-max_load_factor " + max_load_factor + " " +
			"-snes_monitor -save_all -hdf5_out -response -nodal_stress " +
			"-mat " + matFilePath;
		
		CommandRunner.run(cmd);
		
		addOutputFile("h5", "Feawd.out.h5");
		addOutputFile("node_id", "Node_id.txt");
		
		return writeOutputContextXML();
	}
}
