package edu.utep.trustlab.toolkitOperators.cmmf;
import edu.utep.trustlab.toolkitOperators.ToolkitOperator;
import edu.utep.trustlab.toolkitOperators.util.CommandRunner;


public class GenGeo extends ToolkitOperator
{
	/* Is the data this operator processes encoded in ASCII?
	 * If you specify true, then (String stringData) variable will be populated.
	 * Otherwise, (byte[] binaryData) variable will be populated.
	 */
	private static final boolean isInputDataTextual = false;
	
	// Should the input dataset be persisted in a buffer?
	private static final boolean shouldPersistInMemory = false;
	
	// the output name for the dataset generated by this operator
	private static final String outputFileName = "GenGeo_out.xml";
	
	public GenGeo(String datasetURL) {
		super(datasetURL, isInputDataTextual, shouldPersistInMemory, outputFileName);
	}

	/*
	 * This method accesses the functionality of the wrapped executable. In this example, the exectuable takes
	 * three params (param1, param2, and param3). You can extend this to take as many parameters as necessary. This
	 * examples assume that the executable takes an input file path and an output file path, where the result will be written.
	 */
	/* 
	   Jobname – base name for all subsequent files(string)
	   #grains – number of grains to be create in the sample (int)
	   scale – dimension of overall sample (float)
	*/
	public String transform(
			String jobname,
			String ngrains,
			String scale)
	{
		//The command string that will be passed to the shell
		// sh GenGeo jobname #grains scale
		String cmd =
			"sh GenGeo " +
			jobname + " " +
			ngrains + " " +
			scale + " ";
		
		//FileUtils.getOutputURLPrefix();
		//FileUtils.getWorkspace();
		
		CommandRunner.run(cmd);
		
		String[] outputFileNames = { jobname + ".pts", jobname + ".cfg", jobname + ".vtk"};
		setUpMultipleOutputs(outputFileNames);
		
		return outputURL;
	}
}
